"""Add SystemSettings model for embedding configuration

Revision ID: 16e7379fb456
Revises: g6b3f9d20e54
Create Date: 2026-02-17 08:48:08.963487

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16e7379fb456'
down_revision: Union[str, None] = 'g6b3f9d20e54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('embedding_provider', sa.String(length=50), nullable=True, comment="'ollama' vagy 'openrouter'"),
    sa.Column('embedding_model', sa.String(length=255), nullable=True, comment='A használt embedding modell neve'),
    sa.Column('embedding_dimension', sa.Integer(), nullable=True, comment='Az embedding vektor dimenziója'),
    sa.Column('ollama_url', sa.String(length=500), nullable=True, comment='Ollama szerver URL'),
    sa.Column('openrouter_api_key', sa.String(length=500), nullable=True, comment='OpenRouter API kulcs (titkosítva kellene tárolni)'),
    sa.Column('openrouter_embedding_url', sa.String(length=500), nullable=True, comment='OpenRouter API endpoint'),
    sa.Column('chat_provider', sa.String(length=50), nullable=True),
    sa.Column('chat_model', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
